apache:
    build: ./build/httpd
    links:
        - php
    ports:
        - 80:80
        - 443:443
    volumes_from:
        - app

php:
    build: ./build/php
    expose:
        - 9000
    volumes_from:
        - app
    links:
        - mariadb

app:
    image: httpd:latest
    volumes:
        - ./:/var/www/html
    command: "echo true"

mariadb:
    image: mariadb:latest
    volumes:
        - ./build/data:/docker-entrypoint-initdb.d
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: "12345"
        MYSQL_DATABASE: awesome
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: "12345"

data:
    image: mariadb:latest
    volumes:
        - /var/lib/mysql
    command: "true"
