apache:
    build: ./httpd
    links:
        - php
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./:/var/www/html

php:
    build: ./php
    expose:
        - 9000
    volumes:
        - ./:/var/www/html
