apache:
    build: ./httpd
    links:
        - php
    ports:
        - 80:80
        - 443:443
    volumes_from:
        - app

php:
    build: ./php
    expose:
        - 9000
    volumes_from:
        - app
    links:
        - mysql

app:
    image: httpd:latest
    volumes:
        - ./:/var/www/html
    command: "echo true"

mariadb:
    image: mariadb:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: "[123456]"
        MYSQL_DATABASE: awesome.dev
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: "[123456]"

data:
    image: mariadb:latest
    volumes:
        - /var/lib/mysql
    command: "true"
