apache:
    build: ./httpd
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./:/var/www/html

php:
    image: php:5.6.30-fpm
    expose:
        - 9000
    volumes:
        - ./:/var/www/html
